obsproject/obs-plugintemplate

- CMakeLists.txt
Fixes an issue where Windows builds aren't packaged properly, due to a wrong CMake configuration.
Fixes #2 
Checking the contents of the Zip archive generated by CI.
> cmake(win): fix OR conditionals

- .cmake-format.json
- .github/scripts/utils.zsh/check_macos
- CMakeLists.txt
- cmake/ObsPluginHelpers.cmake
Same changes as https://github.com/obsproject/obs-studio/pull/6782 but for the template.
Allow to automatically use whether Qt5 or Qt6 is available and if both are present **prefer Qt6**.
https://github.com/obsproject/obs-studio/pull/6782 proves that the macro is functional.
> Refactor find_qt CMake macro to select Qt version automatically if not specified

- buildspec.json
Use Qt6 by default
Since most developers will be using newer Linux and targeting OBS 28, default to Qt6
Building plugin
> Update buildspec to use Qt6 on Linux

- .github/workflows/main.yml
- Removed unused date env variable
- Also removed commit hash variable, as it isn't needed anymore
- Simplify upload paths
- Removed extra line above job
- Set as prerelease if beta or rc
Workflow simplication
Made release
> Cleanup make-release job

- .cmake-format.json
- CMakeLists.txt
- cmake/ObsPluginHelpers.cmake
Update cmake-format configuration to increase hard column limit to 100 characters.
To improve readability on modern displays and systems, it is considered good practice to encourage an 80-column limit but set the actual hard limit to 100 columns.
The changes in this PR serve as a good example for the improvements in legibility and readability this gives.
CMake files have been updated according to the new rules in this PR.
> cmake: Update cmake-format to allow files to use up to 100 columns

- .github/scripts/check-cmake.sh
- .github/scripts/check-format.sh
The scripts would fail if these directories were present.
Found when formatting plugin.
Ran script to see if it didn't fail
> Ignore build_x86_64/release dirs in format scripts

- .github/scripts/.build.zsh
- CMakeLists.txt
- buildspec.json
- cmake/ObsPluginHelpers.cmake
Makes requirement of Qt and obs-frontend-api optional by requiring the CMake option `ENABLE_GUI` to be set (which is OFF by default) and also improve generation of Xcode projects for macOS development.
Additionally the same compiler settings as used on the main repo have been moved into the CMake helper function, with a few settings removed from the main CMake script.
_If_ a developer wants to dive into the default settings, the helper script has received extensive descriptive comments.
Reduce unnecessary dependencies on Qt and the frontend-api for plugins that don't need it and improve code documentation.
Configured and build the plugintemplate with Xcode locally.
- Documentation (a change to documentation pages)
> CMake: Make UI dependencies optional and synchronise project settings

- cmake/bundle/windows/installer-Windows.iss.in
Because of course the directory exists, it's a plugin.
Don't want confusing dialogs popping up to users
Used in obs-websocket
> Disable the "Directory already exists" warning in Windows installer

- CMakeLists.txt
- cmake/bundle/windows/resource.rc.in
Add resource file for windows builds
Allows users to see version of the plugin dll in the file properties on windows
- New feature (non-breaking change which adds functionality)
> Add windows resource

- .github/workflows/main.yml
Removes Windows 32-bit from the GItHub workflow.
Since OBS 28 doesn't support 32-bit, it is pointless to build 32-bit by default. If developers need 32-bit for whatever reason, they can just add this line back in, as the backend scripts still support it.
Ran workflow.
> Remove Windows 32-bit

- buildspec.json
Updates buildspec file to use latest OBS.
Don't use outdated OBS.
Tested with building plugin.
> Use latest OBS with buildspec

- .github/scripts/.build.zsh
This matches what is default in OBS Studio. Most developers won't
know to change this, as the deb file will install to the wrong place,
causing the plugin not to load.
Got frustrated when installing the deb file, and the plugin wouldn't load. Found out LINUX_PORTABLE was set to ON.
Installed via deb and the plugin loaded successfully.
> Set LINUX_PORTABLE to off on CI

- CMakeLists.txt
This is a trivial reformatting of the set_target_properties line that is used when Qt is included in the plugin. Without reformatting the line, the cmake format check will fail in CI when Qt support is incommented in CMakeLists.txt.
The lines in question will need to be reformatted regardless when uncommented. By making the change here in the template the line will already be formatted correctly, which reduces the diff between the base template and any plugin project that uses the template.
Tested by rebuilding the plugin with Qt support enabled on a MacOS machine.
> cmake: Reformat commented out lines to pass cmake format check

- .github/scripts/.build.zsh
- .github/scripts/.package.zsh
- buildspec.json
Adds support for building linux-aarch64 (Arm) to the CI scripts. The change
matches the configuration used for linux-x86_64 builds.
It is useful to use the .github/scripts/build-linux.sh script for building on a local machine, and not just for GitHub actions. By adding AArch64 in this way I'm able
to test the Linux build on my M1 MacBook with a Linux VM.
Tested on a local M1 MacBook with a Parallels virtual machine running a fresh install of Ubuntu. Also pushed out to GitHub so that Actions can test the other build architectures.
> Add linux-aarch64 support to build scripts

- .github/scripts/Build-Windows.ps1
PowerShell's Out-File cmdlet by default writes a newline at the end of the file. We can prevent this either by manually trimming the whitespace before sending the output to Out-File, or simply using the -NoNewline parameter for Out-File.
Fixes obsproject/obs-plugintemplate#49.
I'm open to discussion on which approach is better.
Don't want unnecessary diffs.
Checked locally on Windows 11.
> Prevent extra newlines in CMakeLists.txt after building

- .github/workflows/main.yml
This generates the plugin name based on the name in the buildspec file.
One less file for developers to change.
Ran workflow.
> Auto generate plugin name in workflow

- .github/workflows/main.yml
Adding the contents write permission enables the make-release job to create a release.
A GitHub Actions job has read-only permission by default and it cannot create releases without configurations. 
Tested on my plugin repository.
https://github.com/umireon/obs-pokemon-sv-helper
> Add contents write permission to create release

- CMakeLists.txt
- cmake/bundle/windows/installer-Windows.iss.in
Fixes #70.
Supersedes #71 as the correct fix rather than placeholder. Keeps original authorship from #71 as well.
Adds a variable to cmake for specifying the website, and changes the default to example.com which is safer than mywebsite.com.
Don't like bad websites.
Tested locally, works
> Use `example.com` as placeholder, fixes #70

- .github/scripts/utils.zsh/read_codesign_pass
read_codesign_pass uses log_warning but it did not have it as autoload. This commit adds log_warning to autoload.
Codesign fails due to command not found error and I need to fix this.
I confirmed this change works in https://github.com/royshil/obs-backgroundremoval/pull/357.
> CI: Fix missing autoload log_warning in read_codesign_pass

- .github/scripts/utils.zsh/setup_linux
This installs OBS Studio from the OBS ppa. This is a temporary fix to prevent the CI from failing if a developer uses newer code then what the unofficial Ubuntu repo provides (27.2.3 on 22.04). This isn't ideal as it installs the entire program instead of just dev packages. In the future, we would provide a libobs-dev package on our ppa.
CI currently fails if developers use newer OBS apis.
Ran CI with one of my plugins
> Install obs-studio from ppa

- .github/actions/package-plugin/action.yaml
- .github/workflows/build-project.yaml
The current workflow fails when it builds the macOS package with nortorization.
https://github.com/umireon/obs-pokemon-sv-screen-builder/actions/runs/5471889748/jobs/9963806267#step:7:375
This PR fix the workflow to provide CODESIGN_TEAM to the packaging action.
Releasing the obs plugin always fails and I cannot release the package so I need to fix this problem.
This change fix the problem on my repository.
https://github.com/umireon/obs-pokemon-sv-screen-builder/actions/runs/5474739649/jobs/9969905028
> CI: Fix missing codesign team on packaging

- cmake/common/compiler_common.cmake
C17 is not supported until CMake 3.21 and C17 must be used with CMake 3.21 or above.
https://cmake.org/cmake/help/latest/prop_tgt/C_STANDARD.html
CMake 3.20 is provided on openSUSE Leap 15.5 and the plugin building with CMake commands fails with the message that CMake does not understand the C standard of C17.
I need this bug to be fixed to build on openSUSE Leap.
This change is tested in our plugin.
https://github.com/royshil/obs-backgroundremoval/pull/430
The building log of our plugin with this change is available:
https://pmbs.links2linux.org/package/live_build_log/home:umireon/obs-backgroundremoval/15.5/x86_64
> cmake: Use C17 only with CMake 3.21 or above

- cmake/windows/helpers.cmake
Fix output directory for target installation into an active `obs-studio` build tree.
Fixes https://github.com/obsproject/obs-plugintemplate/issues/93.
Tested on Windows 11 with existing `obs-studio` build directory.
> cmake: Fix optional target installation into wrong plugin directory

- .github/workflows/build-project.yaml
Also updating `.github\workflows\build-project.yaml` with a few of the latest compatible changes in obs-studio's same file.
Fixing `.github/workflows/build-project.yaml` `GITHUB_EVENT_NAME` `pull_request` `gh` failing and reporting "could not determine current branch".
`.github\workflows\build-project.yaml` has some code that supports packaging the plugin with a `Seeking Testers` label.
https://github.com/obsproject/obs-plugintemplate/blob/57cdde9d8120b7b196a2c4612131b3078f893ad9/.github/workflows/build-project.yaml#L32-L36
This wasn't working because `gh` complained "could not determine current branch":
https://github.com/obsproject/obs-plugintemplate/actions/runs/6657042057/job/18090925431 
This code is based on obs-studio's:
https://github.com/obsproject/obs-studio/blob/64be5a7f9a90c6d2 …
> CI: Fix `pull_request` gh "could not determine current branch"

- cmake/common/helpers_common.cmake
Adding `-fPIC` on Linux when compiling the `libplugin-support.a` static lib, otherwise some Linux OSs build complain e.g.
```
/usr/bin/ld: libplugin-support.a(plugin-support.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
```
Fixing Linux build for OSs such as Fedora.
Built on Mac, Windows and Linux (Ubuntu).
Effectively a bugfix?
> Build plugin support library with PIC on Linux and BSD

- cmake/windows/compilerconfig.cmake
- cmake/windows/helpers.cmake
This is a bugfix written by PatTheMav for obs-studio which applies equally to obs-plugintemplate.
Quote [1]:
CMake 3.25 changed the way PDB generation is handled by only enabling it for Debug and RelWithDebInfo builds, which prohibits generation of fully optimized builds with associated symbols (which is MSVC's default).
If configuring with CMake 3.25 or above, enable this globally for builds using MSVC and fall back to embedded debug information for anything else (which would probably be clang-cl)
CI builds tags as Release. As a result, there's no pdb generated.
It is desirable to ship pdb for better user support.
Tested on a third-party plugin.
The pdb are generated now in Release builds.
> cmake: Force PDB generation on Windows for MSVC builds in all configs

- .clang-format
- src/plugin-support.c.in
Updated to https://github.com/obsproject/obs-studio/blob/93f5b45be8c8b91199c52cf7a0ab59d8c3a08760/.clang-format#L208
Fixes the `.clang-format` file to conform with https://clang.llvm.org/docs/ClangFormatStyleOptions.html.
I like to use CLion for C++ development, so having this file error out was bugging me.
Opened the files of interes in CLion and checked the 'problems' window. Also, I used CLion 'Reformat code' action to reformat the code according to the file.
> Update .clang-format to match obs-studio project 

- .github/scripts/Package-Windows.ps1
Change `Package-Windows.ps1` from:
```
if ( ( $BuildInstaller ) ) {
// package .msi
} else {
// generate .zip
}
```
to
```
// generate .zip
if ( ( $BuildInstaller ) ) {
// package .msi
}
```
The current code either packages a .msi **or** generates a .zip.  
Many users prefer the zip (and it has the benefit of mitigating code signing warnings).  
This change always generates the .zip file.  
If `-BuildInstaller` is also specified then is **also** builds a .msi.
`.github/scripts/Build-Windows.ps1 -SkipDeps && .github/scripts/Package-Windows.ps1 -BuildInstaller` outputs both .zip and .msi
`.github/scripts/Build-Windows.ps1 -SkipDeps && .github/scripts/Package-Windows.ps1` outputs .zip
Do we need to document any changes in this …
> CI: Set Windows packaging to default to zip

- .github/workflows/build-project.yaml
- .github/workflows/push.yaml
- buildspec.json
Adds early detection of the configured plugin name in workflows so the name can be re-used in later workflows without the need to do a full repository checkout or installation of 3rd party utilities (e.g. the release creation step).
Reduce necessary fixup steps for plugin developers when finalising their releases.
Fixes https://github.com/obsproject/obs-plugintemplate/issues/105.
Tested with a tagged release on a fork of the repository.
- Performance enhancement (non-breaking change which improves efficiency)
> CI: Expose detected plugin name to other workflow jobs

- .github/actions/run-clang-format/action.yaml
- build-aux/.run-format.zsh
Upgrade clang-format used in actions to 16
With changes introduced in https://github.com/obsproject/obs-plugintemplate/pull/82 clang-format 16 is now required. Using the current version of 13 will result in a `.clang-format:115:3: error: unknown enumerated scalar` error
I have made small edits to code files which should trigger the github action which I will then revert.
I have also implemented this change into my own plugin after merging latest. https://github.com/EZ64cool/obs-hadowplay/actions/workflows/pr-pull.yaml?query=branch%3Amerging_template
> Update clang-format to 16

- CMakePresets.json
Move ENABLE_FRONTEND_API and ENABLE_QT from individual presets to a common preset that is hidden but inherited by the individual presets.
Generally, these will have the same values on all platforms. Make it easier for plugin devs to enable or disable Frontend API and Qt for all presets/platforms.
Devs can still override this per preset if needed by simply setting a different value in an individual preset.
Fixes #103
Haven't tested locally. CI should be able to test.
> cmake: Move common variables to an inherited preset

- .github/workflows/build-project.yaml
- .github/workflows/check-format.yaml
- .github/workflows/push.yaml
GitHub Actions has deprecated Actions based on node16. The v4 actions are based on node20. Replace first-party v3 actions with their v4 counterparts.
See:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Want to prevent deprecation warnings on CI. Want to avoid CI failing when the node16 actions are disabled.
CI will test.
> CI: Update first-party GitHub Actions from v3 to v4

- .github/actions/run-clang-format/action.yaml
- build-aux/.run-format.zsh
Update clang-format to 17.
Want to match obs-studio.
I haven't tested this on CI. There appear to be no formatting changes to the files in `src/` with clang-format 17.0.3. I checked locally on Windows 11.
> Update clang-format to 17

- .github/workflows/push.yaml
The softprops/action-gh-release action is the last remaining action in this repo that was still using node16. Updating should remove the associated warnings.
Want less CI warnings so the meaningful warnings stand out.
It hasn't. I'm not sure how to test it, but I think @PatTheMav has done it in the past?
> CI: Update softprops/action-gh-release to v2.0.4

- .cmake-format.json
- CMakeLists.txt
- CMakePresets.json
- cmake/common/helpers_common.cmake
This is a port of https://github.com/obsproject/obs-studio/pull/9263 (https://github.com/obsproject/obs-studio/commit/9d611a064f042cec6cba1d64818c8e810ebc4744).
This does not remove `find_qt`, but just forces it to Qt 6 for now.
We no longer support building OBS Studio with Qt 5.
I haven't tested this, This is a port of an existing commit, which has been tested.
> cmake: Remove Qt version selection and Qt 5 support

- .github/workflows/push.yaml
Without this fix the .deb package for ubuntu are not found and does not appear on the release assets
This fixes the missing Ubuntu .deb in release asset, which was dropped because the version of Ubuntu in the renaming step mismatched with Ubuntu deb file naming (22.04 vs 24.04)
Because I use this template and the .deb was missing from the release assets
I checked that the .deb was in the release assets
CI Bug fix (non-breaking change which fixes an issue)
> CI: Fix the Ubuntu version that prevents renaming

- cmake/windows/defaults.cmake
Fix the wrong default value in cmake script.
The default installation for Windows in cmake script is wrong. OBS won't load plugin from there.
from
https://github.com/obsproject/obs-studio/blob/31.0.1/UI/window-basic-main.cpp#L201
```int ret = GetProgramDataPath(base_module_dir, sizeof(base_module_dir), "obs-studio/plugins/%module%");```
https://github.com/obsproject/obs-studio/blob/31.0.1/UI/window-basic-main.cpp#L211
```string path = base_module_dir;```
https://github.com/obsproject/obs-studio/blob/31.0.1/UI/window-basic-main.cpp#L231
```obs_add_module_path((path + "/bin/64bit").c_str(), (path + "/data").c_str());```
My plugin works.
Bug fix
> cmake: Fix default installation directory for Windows

- cmake/macos/compilerconfig.cmake
Follow OBS's Master branch : https://github.com/obsproject/obs-studio/blob/master/cmake/macos/compilerconfig.cmake
Fix errors when macOS SDK is not detected when using cmake 4.0.0+
Developer using cmake 4.0.0 cannot compile plugins and get an error that the macos Version is too low.
The previous SDK detection process return an empty value for the version of the SDK
Confirmed it solved the problem as part of the developement of the [DistroAV plugin](https://github.com/DistroAV/DistroAV/)
Bug fixs for user on MacOS and Cmake 4.0.0+
> cmake: Adjust macOS SDK detection

- .clang-format
- .github/actions/build-plugin/action.yaml
- .github/actions/run-clang-format/action.yaml
- .github/scripts/utils.zsh/check_macos
- CMakePresets.json
- build-aux/.run-format.zsh
- buildspec.json
- cmake/common/buildspec_common.cmake
This PR updates open issues of the plugin template that have arisen since the last major release of OBS Studio:
* Updates build specification to use OBS Studio 31.1.1 and associated dependencies (obs-deps and Qt6)
* Updates OBS Studio build flags according to upstream renaming of "UI" to "frontend" to ensure that no frontend targets are built to generate the `libobs` library
* Updates `clang-format` to use version 19.1.1 to stay in sync with OBS Studio
* Updates the `clang-format` rules to stay in sync with OBS Studio
* Removes the macOS host check script as the check is implemented in CMake already, also removes the maintenance burden of keeping both values in sync manually.
* macOS deployment target is increased to 12.0 in sync with Qt 6.8 and OBS Studio
* Adds the missing assignment of …
> Update plugin template to support OBS Studio 31.1.1
